-- ============================================================
-- 06_reset_pembayaran_dan_urutkan_donatur.sql
-- 1. Kosongkan tabel pembayaran
-- 2. Urutkan ulang ID donatur mulai dari 1 s.d. N
-- 3. Reset sequence auto-increment donatur
-- ============================================================

-- 1. Kosongkan tabel pembayaran
TRUNCATE TABLE public.pembayaran CASCADE;

-- 2. Izinkan penataan nilai ID secara manual pada tabel donatur
ALTER TABLE public.donatur ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 3. Tahap A: Geser ID ke nilai sementara (10000 + urutan) agar tidak bentrok dengan primary key unik
WITH mapping_baru AS (
  SELECT id AS id_lama, ROW_NUMBER() OVER (ORDER BY id ASC) AS no_urut
  FROM public.donatur
)
UPDATE public.donatur d
SET id = m.no_urut + 10000
FROM mapping_baru m
WHERE d.id = m.id_lama;

-- 4. Tahap B: Kembalikan ID ke nilai urut baru (1, 2, 3, ...)
WITH final_mapping AS (
  SELECT id AS id_temp, id - 10000 AS id_final
  FROM public.donatur
  WHERE id > 10000
)
UPDATE public.donatur d
SET id = f.id_final
FROM final_mapping f
WHERE d.id = f.id_temp;

-- 5. Sinkronkan sequence auto-increment PostgreSQL ke MAX(id) donatur
-- sehingga donatur baru yang didaftarkan berikutnya akan otomatis mendapat ID (171, 172, dst)
SELECT setval(
  pg_get_serial_sequence('public.donatur', 'id'),
  COALESCE((SELECT MAX(id) FROM public.donatur), 1)
);
